//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citPOINT.eNeg.ViewModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("citPOINT.eNeg.ViewModel.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your account is disabled.
        ///Contact you administrator to enable it..
        /// </summary>
        public static string AccountDisabled {
            get {
                return ResourceManager.GetString("AccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your account is Locked, If you have just been registered, so you need to activate your account using activation link sent to your mail..
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You accept to bacame owner in the organization..
        /// </summary>
        public static string ActivateOrgOwnerSucess {
            get {
                return ResourceManager.GetString("ActivateOrgOwnerSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your activation process completed successfully..
        /// </summary>
        public static string ActivationMailSuccess {
            get {
                return ResourceManager.GetString("ActivationMailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel any changes, are you sure?.
        /// </summary>
        public static string CancelAnyChangesMessageBoxText {
            get {
                return ResourceManager.GetString("CancelAnyChangesMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel editing current Item, are you sure?.
        /// </summary>
        public static string CancelCurrentItemMessageBoxText {
            get {
                return ResourceManager.GetString("CancelCurrentItemMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string ConfirmMessageBoxCaption {
            get {
                return ResourceManager.GetString("ConfirmMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another conversation with the same name..
        /// </summary>
        public static string ConversationRepeat {
            get {
                return ResourceManager.GetString("ConversationRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete?.
        /// </summary>
        public static string DeleteCurrentItemMessageBoxText {
            get {
                return ResourceManager.GetString("DeleteCurrentItemMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must Activate your account first.
        /// </summary>
        public static string EmailNotActive {
            get {
                return ResourceManager.GetString("EmailNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email is not registered.
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already registered before..
        /// </summary>
        public static string EmailRepeated {
            get {
                return ResourceManager.GetString("EmailRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eNeg Information.
        /// </summary>
        public static string eNegInformation {
            get {
                return ResourceManager.GetString("eNegInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting PDF completed sucessfully.
        /// </summary>
        public static string ExportDone {
            get {
                return ResourceManager.GetString("ExportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is invalid confirmation mail or you have used it before..
        /// </summary>
        public static string InvalidConfirmationMail {
            get {
                return ResourceManager.GetString("InvalidConfirmationMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format (e.g, &quot;Me-user@mailserver.com&quot; or &quot;user@mailserver.com&quot;).
        /// </summary>
        public static string InvalidNegotiatorName {
            get {
                return ResourceManager.GetString("InvalidNegotiatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Negotation(s) already published..
        /// </summary>
        public static string NegotaionAlreadyPublished {
            get {
                return ResourceManager.GetString("NegotaionAlreadyPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another negotiation with the same name..
        /// </summary>
        public static string NegotiationRepeat {
            get {
                return ResourceManager.GetString("NegotiationRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string NewUserCreatedCaption {
            get {
                return ResourceManager.GetString("NewUserCreatedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive now an email to activate your account..
        /// </summary>
        public static string NewUserCreatedText {
            get {
                return ResourceManager.GetString("NewUserCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to see this profile..
        /// </summary>
        public static string NotAuthorizedProfile {
            get {
                return ResourceManager.GetString("NotAuthorizedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t own another organization.You are owner for organization &quot;{0}&quot;..
        /// </summary>
        public static string OnlyOneOrganizationOwner {
            get {
                return ResourceManager.GetString("OnlyOneOrganizationOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Organization mails Sent successfully.
        /// </summary>
        public static string OrganizationMailSuccess {
            get {
                return ResourceManager.GetString("OrganizationMailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another organization with the same name..
        /// </summary>
        public static string OrganizationRepeat {
            get {
                return ResourceManager.GetString("OrganizationRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This receiver is exist..
        /// </summary>
        public static string ReceiverExist {
            get {
                return ResourceManager.GetString("ReceiverExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You refused to became owner in the organization.
        /// </summary>
        public static string RefuseOrgOwnerSucess {
            get {
                return ResourceManager.GetString("RefuseOrgOwnerSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove this user ?.
        /// </summary>
        public static string RemoveCurrentUserMessageBoxText {
            get {
                return ResourceManager.GetString("RemoveCurrentUserMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is invalid reset mail or you have used it before..
        /// </summary>
        public static string RequestReset {
            get {
                return ResourceManager.GetString("RequestReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset success..
        /// </summary>
        public static string ResetSuccess {
            get {
                return ResourceManager.GetString("ResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Saved Successfully.
        /// </summary>
        public static string SaveMessageSucess {
            get {
                return ResourceManager.GetString("SaveMessageSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization updated Successfully..
        /// </summary>
        public static string UpdateManageOrganizationSuccess {
            get {
                return ResourceManager.GetString("UpdateManageOrganizationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated Successfully.
        ///You will receive now an email with a link to activate your New account..
        /// </summary>
        public static string UpdateMyProfileAndUserEmail {
            get {
                return ResourceManager.GetString("UpdateMyProfileAndUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated Successfully..
        /// </summary>
        public static string UpdateMyProfileSuccess {
            get {
                return ResourceManager.GetString("UpdateMyProfileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should be a member in any organization to can publish to it..
        /// </summary>
        public static string UserHaveNotOrganization {
            get {
                return ResourceManager.GetString("UserHaveNotOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name must be more than one character..
        /// </summary>
        public static string ValidateErrorYourNameLenght {
            get {
                return ResourceManager.GetString("ValidateErrorYourNameLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string ValidationErrorRequiredField {
            get {
                return ResourceManager.GetString("ValidationErrorRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-mail or password is incorrect. 
        ///Please try again..
        /// </summary>
        public static string WrongCredentials {
            get {
                return ResourceManager.GetString("WrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect.
        ///Please try again..
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive now an email with a link to change your user data..
        /// </summary>
        public static string YouNewMail {
            get {
                return ResourceManager.GetString("YouNewMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry,you can&apos;t leave this organization untill you choose another organization owner.
        ///If you click OK you will go to Manage Organization and lost your changes.
        ///Do you need to Continue ?.
        /// </summary>
        public static string YouWantToLeaveOrg {
            get {
                return ResourceManager.GetString("YouWantToLeaveOrg", resourceCulture);
            }
        }
    }
}
