//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace citPOINT.eNeg.Data.Web
{
    public partial class ActionType
    {
        #region Primitive Properties
    
        public virtual System.Guid ActionTypeID
        {
            get;
            set;
        }
    
        public virtual string ActionDescription
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<History> Histories
        {
            get
            {
                if (_histories == null)
                {
                    var newCollection = new FixupCollection<History>();
                    newCollection.CollectionChanged += FixupHistories;
                    _histories = newCollection;
                }
                return _histories;
            }
            set
            {
                if (!ReferenceEquals(_histories, value))
                {
                    var previousValue = _histories as FixupCollection<History>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupHistories;
                    }
                    _histories = value;
                    var newValue = value as FixupCollection<History>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupHistories;
                    }
                }
            }
        }
        private ICollection<History> _histories;

        #endregion
        #region Association Fixup
    
        private void FixupHistories(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (History item in e.NewItems)
                {
                    item.ActionType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (History item in e.OldItems)
                {
                    if (ReferenceEquals(item.ActionType, this))
                    {
                        item.ActionType = null;
                    }
                }
            }
        }

        #endregion
    }
}
