//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace citPOINT.eNeg.Data.Web
{
    public partial class Channel
    {
        #region Primitive Properties
    
        public virtual System.Guid ChannelID
        {
            get;
            set;
        }
    
        public virtual string ChannelName
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> ChannelTypeID
        {
            get { return _channelTypeID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_channelTypeID != value)
                    {
                        if (ChannelType != null && ChannelType.ChannelTypeID != value)
                        {
                            ChannelType = null;
                        }
                        _channelTypeID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<System.Guid> _channelTypeID;

        #endregion
        #region Navigation Properties
    
        public virtual ChannelType ChannelType
        {
            get { return _channelType; }
            set
            {
                if (!ReferenceEquals(_channelType, value))
                {
                    var previousValue = _channelType;
                    _channelType = value;
                    FixupChannelType(previousValue);
                }
            }
        }
        private ChannelType _channelType;
    
        public virtual ICollection<Message> Messages
        {
            get
            {
                if (_messages == null)
                {
                    var newCollection = new FixupCollection<Message>();
                    newCollection.CollectionChanged += FixupMessages;
                    _messages = newCollection;
                }
                return _messages;
            }
            set
            {
                if (!ReferenceEquals(_messages, value))
                {
                    var previousValue = _messages as FixupCollection<Message>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMessages;
                    }
                    _messages = value;
                    var newValue = value as FixupCollection<Message>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMessages;
                    }
                }
            }
        }
        private ICollection<Message> _messages;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupChannelType(ChannelType previousValue)
        {
            if (previousValue != null && previousValue.Channels.Contains(this))
            {
                previousValue.Channels.Remove(this);
            }
    
            if (ChannelType != null)
            {
                if (!ChannelType.Channels.Contains(this))
                {
                    ChannelType.Channels.Add(this);
                }
                if (ChannelTypeID != ChannelType.ChannelTypeID)
                {
                    ChannelTypeID = ChannelType.ChannelTypeID;
                }
            }
            else if (!_settingFK)
            {
                ChannelTypeID = null;
            }
        }
    
        private void FixupMessages(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Message item in e.NewItems)
                {
                    item.Channel = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Message item in e.OldItems)
                {
                    if (ReferenceEquals(item.Channel, this))
                    {
                        item.Channel = null;
                    }
                }
            }
        }

        #endregion
    }
}
