//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace citPOINT.eNeg.Data.Web
{
    public partial class ChannelType
    {
        #region Primitive Properties
    
        public virtual System.Guid ChannelTypeID
        {
            get;
            set;
        }
    
        public virtual string TypeName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Channel> Channels
        {
            get
            {
                if (_channels == null)
                {
                    var newCollection = new FixupCollection<Channel>();
                    newCollection.CollectionChanged += FixupChannels;
                    _channels = newCollection;
                }
                return _channels;
            }
            set
            {
                if (!ReferenceEquals(_channels, value))
                {
                    var previousValue = _channels as FixupCollection<Channel>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupChannels;
                    }
                    _channels = value;
                    var newValue = value as FixupCollection<Channel>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupChannels;
                    }
                }
            }
        }
        private ICollection<Channel> _channels;

        #endregion
        #region Association Fixup
    
        private void FixupChannels(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Channel item in e.NewItems)
                {
                    item.ChannelType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Channel item in e.OldItems)
                {
                    if (ReferenceEquals(item.ChannelType, this))
                    {
                        item.ChannelType = null;
                    }
                }
            }
        }

        #endregion
    }
}
