//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace citPOINT.eNeg.Data.Web
{
    public partial class History
    {
        #region Primitive Properties
    
        public virtual System.Guid HistoryID
        {
            get;
            set;
        }
    
        public virtual string OldValue
        {
            get;
            set;
        }
    
        public virtual string NewValue
        {
            get;
            set;
        }
    
        public virtual string TableName
        {
            get;
            set;
        }
    
        public virtual System.Guid ActionTypeID
        {
            get { return _actionTypeID; }
            set
            {
                if (_actionTypeID != value)
                {
                    if (ActionType != null && ActionType.ActionTypeID != value)
                    {
                        ActionType = null;
                    }
                    _actionTypeID = value;
                }
            }
        }
        private System.Guid _actionTypeID;
    
        public virtual System.DateTime ActionDate
        {
            get;
            set;
        }
    
        public virtual System.Guid UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    if (User != null && User.UserID != value)
                    {
                        User = null;
                    }
                    _userID = value;
                }
            }
        }
        private System.Guid _userID;

        #endregion
        #region Navigation Properties
    
        public virtual ActionType ActionType
        {
            get { return _actionType; }
            set
            {
                if (!ReferenceEquals(_actionType, value))
                {
                    var previousValue = _actionType;
                    _actionType = value;
                    FixupActionType(previousValue);
                }
            }
        }
        private ActionType _actionType;
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private void FixupActionType(ActionType previousValue)
        {
            if (previousValue != null && previousValue.Histories.Contains(this))
            {
                previousValue.Histories.Remove(this);
            }
    
            if (ActionType != null)
            {
                if (!ActionType.Histories.Contains(this))
                {
                    ActionType.Histories.Add(this);
                }
                if (ActionTypeID != ActionType.ActionTypeID)
                {
                    ActionTypeID = ActionType.ActionTypeID;
                }
            }
        }
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.Histories.Contains(this))
            {
                previousValue.Histories.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.Histories.Contains(this))
                {
                    User.Histories.Add(this);
                }
                if (UserID != User.UserID)
                {
                    UserID = User.UserID;
                }
            }
        }

        #endregion
    }
}
