//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace citPOINT.eNeg.Data.Web
{
    public partial class NegotiationArchive
    {
        #region Primitive Properties
    
        public int ArchiveID
        {
            get;
            set;
        }
    
        public Nullable<int> ArchiveYear
        {
            get;
            set;
        }
    
        public Nullable<int> ArchiveMonth
        {
            get;
            set;
        }

        #endregion
    }
}
