//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace citPOINT.eNeg.Data.Web
{
    public partial class NegotiationStatu
    {
        #region Primitive Properties
    
        public virtual System.Guid StatusID
        {
            get;
            set;
        }
    
        public virtual string StatusDescription
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Negotiation> Negotiations
        {
            get
            {
                if (_negotiations == null)
                {
                    var newCollection = new FixupCollection<Negotiation>();
                    newCollection.CollectionChanged += FixupNegotiations;
                    _negotiations = newCollection;
                }
                return _negotiations;
            }
            set
            {
                if (!ReferenceEquals(_negotiations, value))
                {
                    var previousValue = _negotiations as FixupCollection<Negotiation>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupNegotiations;
                    }
                    _negotiations = value;
                    var newValue = value as FixupCollection<Negotiation>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupNegotiations;
                    }
                }
            }
        }
        private ICollection<Negotiation> _negotiations;

        #endregion
        #region Association Fixup
    
        private void FixupNegotiations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Negotiation item in e.NewItems)
                {
                    item.NegotiationStatu = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Negotiation item in e.OldItems)
                {
                    if (ReferenceEquals(item.NegotiationStatu, this))
                    {
                        item.NegotiationStatu = null;
                    }
                }
            }
        }

        #endregion
    }
}
