//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace citPOINT.eNeg.Data.Web
{
    public partial class OrganizationType
    {
        #region Primitive Properties
    
        public virtual int OrganizationTypeID
        {
            get;
            set;
        }
    
        public virtual string OrganizationTypeName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Organization> Organizations
        {
            get
            {
                if (_organizations == null)
                {
                    var newCollection = new FixupCollection<Organization>();
                    newCollection.CollectionChanged += FixupOrganizations;
                    _organizations = newCollection;
                }
                return _organizations;
            }
            set
            {
                if (!ReferenceEquals(_organizations, value))
                {
                    var previousValue = _organizations as FixupCollection<Organization>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupOrganizations;
                    }
                    _organizations = value;
                    var newValue = value as FixupCollection<Organization>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupOrganizations;
                    }
                }
            }
        }
        private ICollection<Organization> _organizations;

        #endregion
        #region Association Fixup
    
        private void FixupOrganizations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Organization item in e.NewItems)
                {
                    item.OrganizationType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Organization item in e.OldItems)
                {
                    if (ReferenceEquals(item.OrganizationType, this))
                    {
                        item.OrganizationType = null;
                    }
                }
            }
        }

        #endregion
    }
}
