//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace citPOINT.eNeg.Data.Web
{
    public partial class Role
    {
        #region Primitive Properties
    
        public virtual System.Guid RoleID
        {
            get;
            set;
        }
    
        public virtual string RoleName
        {
            get;
            set;
        }
    
        public virtual string RoleDescription
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<RoleRight> RoleRight
        {
            get
            {
                if (_roleRight == null)
                {
                    var newCollection = new FixupCollection<RoleRight>();
                    newCollection.CollectionChanged += FixupRoleRight;
                    _roleRight = newCollection;
                }
                return _roleRight;
            }
            set
            {
                if (!ReferenceEquals(_roleRight, value))
                {
                    var previousValue = _roleRight as FixupCollection<RoleRight>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRoleRight;
                    }
                    _roleRight = value;
                    var newValue = value as FixupCollection<RoleRight>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRoleRight;
                    }
                }
            }
        }
        private ICollection<RoleRight> _roleRight;
    
        public virtual ICollection<UserRole> UserRole
        {
            get
            {
                if (_userRole == null)
                {
                    var newCollection = new FixupCollection<UserRole>();
                    newCollection.CollectionChanged += FixupUserRole;
                    _userRole = newCollection;
                }
                return _userRole;
            }
            set
            {
                if (!ReferenceEquals(_userRole, value))
                {
                    var previousValue = _userRole as FixupCollection<UserRole>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUserRole;
                    }
                    _userRole = value;
                    var newValue = value as FixupCollection<UserRole>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUserRole;
                    }
                }
            }
        }
        private ICollection<UserRole> _userRole;

        #endregion
        #region Association Fixup
    
        private void FixupRoleRight(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (RoleRight item in e.NewItems)
                {
                    item.Role = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (RoleRight item in e.OldItems)
                {
                    if (ReferenceEquals(item.Role, this))
                    {
                        item.Role = null;
                    }
                }
            }
        }
    
        private void FixupUserRole(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (UserRole item in e.NewItems)
                {
                    item.Role = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (UserRole item in e.OldItems)
                {
                    if (ReferenceEquals(item.Role, this))
                    {
                        item.Role = null;
                    }
                }
            }
        }

        #endregion
    }
}
