//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace citPOINT.eNeg.Data.Web
{
    public partial class UserLeaveOrganizationResult
    {
        #region Primitive Properties
    
        public Nullable<bool> CanLeave
        {
            get;
            set;
        }
    
        public Nullable<int> OwnersCount
        {
            get;
            set;
        }
    
        public Nullable<System.Guid> AlternativeOwnerID
        {
            get;
            set;
        }
    
        public string EmailAddress
        {
            get;
            set;
        }
    
        public string FirstName
        {
            get;
            set;
        }
    
        public string LastName
        {
            get;
            set;
        }

        #endregion
    }
}
