//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace citPOINT.eNeg.Data.Web
{
    public partial class UserRole
    {
        #region Primitive Properties
    
        public virtual System.Guid UserRoleID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> UserID
        {
            get { return _userID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_userID != value)
                    {
                        if (User != null && User.UserID != value)
                        {
                            User = null;
                        }
                        _userID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<System.Guid> _userID;
    
        public virtual Nullable<System.Guid> RoleID
        {
            get { return _roleID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_roleID != value)
                    {
                        if (Role != null && Role.RoleID != value)
                        {
                            Role = null;
                        }
                        _roleID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<System.Guid> _roleID;

        #endregion
        #region Navigation Properties
    
        public virtual Role Role
        {
            get { return _role; }
            set
            {
                if (!ReferenceEquals(_role, value))
                {
                    var previousValue = _role;
                    _role = value;
                    FixupRole(previousValue);
                }
            }
        }
        private Role _role;
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupRole(Role previousValue)
        {
            if (previousValue != null && previousValue.UserRole.Contains(this))
            {
                previousValue.UserRole.Remove(this);
            }
    
            if (Role != null)
            {
                if (!Role.UserRole.Contains(this))
                {
                    Role.UserRole.Add(this);
                }
                if (RoleID != Role.RoleID)
                {
                    RoleID = Role.RoleID;
                }
            }
            else if (!_settingFK)
            {
                RoleID = null;
            }
        }
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.UserRole.Contains(this))
            {
                previousValue.UserRole.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.UserRole.Contains(this))
                {
                    User.UserRole.Add(this);
                }
                if (UserID != User.UserID)
                {
                    UserID = User.UserID;
                }
            }
            else if (!_settingFK)
            {
                UserID = null;
            }
        }

        #endregion
    }
}
