//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace citPOINT.eNeg.Data.Web
{
    public partial class UserOrganization
    {
        #region Primitive Properties
    
        public virtual System.Guid UserOrganizationID
        {
            get;
            set;
        }
    
        public virtual System.Guid UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    if (User != null && User.UserID != value)
                    {
                        User = null;
                    }
                    _userID = value;
                }
            }
        }
        private System.Guid _userID;
    
        public virtual System.Guid OrganizationID
        {
            get { return _organizationID; }
            set
            {
                if (_organizationID != value)
                {
                    if (Organization != null && Organization.OrganizationID != value)
                    {
                        Organization = null;
                    }
                    _organizationID = value;
                }
            }
        }
        private System.Guid _organizationID;
    
        public virtual byte MemberStatus
        {
            get;
            set;
        }
    
        public virtual bool Deleted
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> DeletedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DeletedOn
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Organization Organization
        {
            get { return _organization; }
            set
            {
                if (!ReferenceEquals(_organization, value))
                {
                    var previousValue = _organization;
                    _organization = value;
                    FixupOrganization(previousValue);
                }
            }
        }
        private Organization _organization;
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private void FixupOrganization(Organization previousValue)
        {
            if (previousValue != null && previousValue.UserOrganizations.Contains(this))
            {
                previousValue.UserOrganizations.Remove(this);
            }
    
            if (Organization != null)
            {
                if (!Organization.UserOrganizations.Contains(this))
                {
                    Organization.UserOrganizations.Add(this);
                }
                if (OrganizationID != Organization.OrganizationID)
                {
                    OrganizationID = Organization.OrganizationID;
                }
            }
        }
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.UserOrganizations.Contains(this))
            {
                previousValue.UserOrganizations.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.UserOrganizations.Contains(this))
                {
                    User.UserOrganizations.Add(this);
                }
                if (UserID != User.UserID)
                {
                    UserID = User.UserID;
                }
            }
        }

        #endregion
    }
}
